"""Universal schema exports (legacy OSINT + SETU AAROGYA DRISHTI)."""

from .core import (
	Entity,
	EntityType,
	EventEntityNotification,
	GraphEntityUpsert,
	GraphRelationshipUpsert,
	GraphWriteBatch,
	RawEvent,
	Relationship,
	TargetURL,
	UniversalSchema,
)
from .health import (
	AdverseEventStatistic,
	AuditEntry,
	ClusterStatistic,
	CodeMapping,
	HealthBaseSchema,
	HealthMention,
	KeywordSet,
	LanguageSegment,
	MedicalAnnotation,
	MedicalEntity,
	MisinformationFlag,
	NormalizedMention,
	PIIFinding,
	PrefilledForm,
	Project,
	SentimentScore,
	Signal,
	SourceConfig,
	SourceHealthSnapshot,
	TextSpan,
	TrendStatistic,
	TriageDecision,
)

__all__ = [
	# Legacy OSINT
	"Entity",
	"EntityType",
	"EventEntityNotification",
	"GraphEntityUpsert",
	"GraphRelationshipUpsert",
	"GraphWriteBatch",
	"RawEvent",
	"Relationship",
	"TargetURL",
	"UniversalSchema",
	# SETU
	"AdverseEventStatistic",
	"AuditEntry",
	"ClusterStatistic",
	"CodeMapping",
	"HealthBaseSchema",
	"HealthMention",
	"KeywordSet",
	"LanguageSegment",
	"MedicalAnnotation",
	"MedicalEntity",
	"MisinformationFlag",
	"NormalizedMention",
	"PIIFinding",
	"PrefilledForm",
	"Project",
	"SentimentScore",
	"Signal",
	"SourceConfig",
	"SourceHealthSnapshot",
	"TextSpan",
	"TrendStatistic",
	"TriageDecision",
]
